# Use Node.js as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json before other files (to leverage Docker cache)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files into the container
COPY . .

# Expose the application port
EXPOSE 5000

# Install nodemon globally
RUN npm install -g nodemon

# Command run the app in  dev mode
CMD ["npm","run","dev"]
